# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
- cron: "*/20 * * * *"
  displayName: "Every 20 minutes schedule"
  branches:
    include:
    - master

pool:
  name: local

steps:
- script: pytest
  displayName: 'Run a one-line script'

- script: |
    cd $(System.DefaultWorkingDirectory)
    echo "Current directory: $(System.DefaultWorkingDirectory)"
  displayName: 'Print Current Directory'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
